### ISSUE TITLE
No idea how to use it

### ISSUE THREAD

**Issue by sTiKyt** [loouislow81/kraft.ui#4]
This is probably wrong place to ask but i have no idea how am i supposed to use it, there is no guide, no wiki, no youtube videos, nothing really... And i'm not willing to spend time figuring it all out on my own when there are other options
Of course you aren't supposed to explain all of that because it's MIT license, etc. but it's just not user friendly i guess?

**Comment by loouislow81** [comment]
> This is probably the wrong place to ask but I have no idea how am I supposed to use it, there is no guide, no wiki, no youtube videos, nothing really... And I'm not willing to spend time figuring it all out on my own when there are other options
> Of course you aren't supposed to explain all of that because it's MIT license, etc. but it's just not user friendly I guess?

I build this concept app is to test my coding skill by just using VanillaJS and UI design skill, meanwhile creating a showcase for those interested in this project for money. The landing page is a showcase of this concept product.
